spring:
  application:
    name: coustomer
server:
  port: 8003

  eureka:
    instance:
      prefer-ip-address: true  #注册服务的时候使用的ip 地址
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/